nm=input("enter your name")
sid=input("enter your sid")
dept=input("enter your department")
cgpa=input("enter yor cgpa")
nm=str(nm)
sid=str(sid)
dept=str(dept)
cgpa=str(cgpa)
print("Hey, ",nm," Here!","\nMy SID is ",sid,"\nI am from ",dept," department and my CGPA is ",cgpa)
